### ISSUE TITLE
Invalid set index 'visible' after install

### ISSUE THREAD

**Issue by BurningSquid** [HungryProton/concept_graph#20]
Followed the instruction for installation on the wiki and am getting the following error when clicking on the ConceptGraph node:

![image](https://user-images.githubusercontent.com/13892894/81623024-11caf280-93b8-11ea-931d-2ed80b6e0208.png)

In the image you can see my setup in terms of the project files. This is a fresh project and I have not edited any scripts prior to the above image.

**Comment by 19PHOBOSS98** [comment]
same. Right as I enabled the plug in I get this:
![Screenshot 2020-05-12 at 11 38 44 AM]
I'm running a Mac by the way

(https://user-images.githubusercontent.com/37253663/81635967-2c977880-9445-11ea-9755-890ff54fd381.jpg)

**Comment by 19PHOBOSS98** [comment]
hey, I think I solved it! what I did was renamed the folder to exactly "concept_graph" right before dropping it in the addons folder. Godot apparently couldn't recognise the folder when it was named "concept_graph-master":
![Screenshot 2020-05-12 at 11 38 44 AM](https://user-images.githubusercontent.com/37253663/81637458-fcea6f80-9448-11ea-9afd-c8516fcf99e5.jpg)

**Comment by 19PHOBOSS98** [comment]
update: now most of the stuff is gone:
![Screenshot 2020-05-12 at 12 13 33 PM](https://user-images.githubusercontent.com/37253663/81637876-06280c00-944a-11ea-8c2d-57a653b96b10.jpg)

**Comment by 19PHOBOSS98** [comment]
> update: now most of the stuff is gone:
> ![Screenshot 2020-05-12 at 12 13 33 PM](https://user-images.githubusercontent.com/37253663/81637876-06280c00-944a-11ea-8c2d-57a653b96b10.jpg)

owp, wait, never mind:
![Screenshot 2020-05-12 at 1 10 05 PM](https://user-images.githubusercontent.com/37253663/81640784-075d3700-9452-11ea-8265-b419448cf50d.jpg)
I don't know what happened there but I did exactly the same thing as before: extracted it, renamed it to "concept_graph" and THEN dropped it in the addons folder and it all worked out in the end :)

**Comment by HungryProton** [comment]
I thought I fixed that already, this is usually because some resources in scripts are referenced with a absolute path instead of a relative one, I'll look into it

**Comment by megaBadger** [comment]
Thanks y'all! I appreciate the help

I swear I did this already but I'm sure I skipped something. Here's how I got it working: 

1) Download zip file
2) Extract to folder and rename "concept_graph" no quotes
3) Create empty Godot project
4) Close out of project
5) Create addons folder in project directory
6) Place concept_graph folder in addons folder
7) Open Godot Project
8) Activate plugin via the project settings menu
9) Adds Concept Graph node
10) Yay it works

![image](https://user-images.githubusercontent.com/13892894/81717549-4c786d80-9440-11ea-97ab-311be5086eab.png)

**Comment by HungryProton** [comment]
So I'm closing the issue if everything works
If you still have issues, feel free to reopen this
