### ISSUE TITLE
Nodes spacing doesn't take into account UI scale. 

### ISSUE THREAD

**Issue by Muzz** [HungryProton/concept_graph#21]
I have 4k monitors. Seems that the spacing on the nodes doesn't take into account the UI scale of GODOT. 

at 100%.
![image](https://user-images.githubusercontent.com/2074204/81630589-61a5ca00-9449-11ea-98f9-9ba135bc22d8.png)

at 150%
![image](https://user-images.githubusercontent.com/2074204/81630625-76825d80-9449-11ea-9da4-4203df289aca.png)

Rad plugin, i'll keep playing and post any more issues I find

**Comment by Muzz** [comment]
Seems quite a few windows don't take this into account. the node search window is another case.

**Comment by HungryProton** [comment]
Thank you for reporting this issue, if I can access this scaling property from the editor script it should be easy to fix

**Comment by Muzz** [comment]
Sadly i don't think it's actually available, from what i was reading in Zylann's height map code. 

https://github.com/Zylann/godot_heightmap_plugin/blob/master/addons/zylann.hterrain/tools/util/editor_util.gd

Thought you may be able to just source the function he wrote from this file to do the job.

**Comment by HungryProton** [comment]
Thanks for the link, that was helpful!
Spacing between nodes should be fixed in ab54bfa1faac3d6f5bd9bb9a103500555afa6a49
The node window is resizable but it still lacks sensible defaults

**Comment by Muzz** [comment]
Awesome, i'll test it out today!
