### ISSUE TITLE
Unable to use materials with the example ground graph

### ISSUE THREAD

**Issue by mikeant42** [HungryProton/concept_graph#22]
Hello, and thanks for opening this awesome tool. I have been playing around with it, and maybe I'm doing something wrong, but I am unable to make the default ground graph work with materials. Here is a picture of my graph.

![graph](https://user-images.githubusercontent.com/8772919/81725304-a5053600-9453-11ea-8a62-08316e859613.png)

The material in the inspector never applies. Funny enough, when making the material anything other than a spatialmaterial the mesh completely disappears.

**Comment by HungryProton** [comment]
My bad, should be fixed in 606502e62df0f2ca71dee177419c58744dbfa6dd
As for why it disappear when using something else that a SpatialMaterial, I'm still looking into it

**Comment by mikeant42** [comment]
Thanks for the quick reply, I actually added to that file `if node is CSGPolygon:    node.material = material` and was wondering why it wasn't working. Maybe I hadn't reloaded the plugin. Oh well, thanks I'll close the issue.
