### ISSUE TITLE
Node Request: Arithmetic Math Node

### ISSUE THREAD

**Issue by orestiskon** [HungryProton/concept_graph#30]
Feel free to delete if this is not relevant.
I couldn't find a simple math node to do arithmetic operations like Add.

Trying to follow the palm tree tutorial, I'd like to combine the Aligned rotations from the "Sample Curve Points" node and the "Rotate Random" node by adding them, but there aren't any such math nodes.
Would that be a correct way to go?

We should be able to add Scalars, or Vectors or Matrices etc.

**Comment by HungryProton** [comment]
There's two new nodes under the Math section.
Feel free to open a new issue if you need more functionality on these two ;)

**Comment by orestiskon** [comment]
They look awesome, thank you for adding them!
