### ISSUE TITLE
Cannot make multimesh out of extruded polygon curve.

### ISSUE THREAD

**Issue by Astavie** [HungryProton/concept_graph#33]
![](http://g2f.nl/0m37jnk)

This outputs nothing. My transforms exist and my polygon exists, yet combined they output nothing,

**Comment by Astavie** [comment]
Basically, I want to make a plank generator (with custom width, height and length), and this is the only way so far I've seen how you'd do that, by extruding a rectangle curve.

**Comment by Astavie** [comment]
Another way it would be possible is by adding some sort of "Scale" node. Right now there's only "scale from noise", but "scale from constant" would also be nice.

**Comment by HungryProton** [comment]
The multimesh issue should be fixed in fd1e1a73c5b160c849b8d394775be98e13d528ae (Will merge with master soon)
I'll take a look at the scale constant, it should be fast to add

**Comment by HungryProton** [comment]
Should be fixed now, feel free to reopen if you still have issues with this
