### ISSUE TITLE
Rotate random is not an offset

### ISSUE THREAD

**Issue by Astavie** [HungryProton/concept_graph#34]
I created a path of plank using a Sample Curve Points node with align rotation:

![](http://g2f.nl/0qr204x)

I wanted to add some random rotation, so I added a Random Rotation node in between Sample Curve Points and Make Multimesh, which resulted in this:

![](http://g2f.nl/0lzcm1m)

As you can see, the align rotation is completely ignored now.

**Comment by HungryProton** [comment]
This was fixed in b153db4d3dee3b643ac54fc6aa3e09d9a6d40353 on the develop branch. It should be merged in master this week end
