### ISSUE TITLE
Deform mesh to curve

### ISSUE THREAD

**Issue by Muzz** [HungryProton/concept_graph#38]
I'm already working on this and have a prototype happening. 

![DeformToCurve](https://user-images.githubusercontent.com/2074204/82111777-ba979a00-978a-11ea-8d8e-6c85a445980d.gif)

Currently it maps the y axis along the curve, but i'll add the ability to customize that. 

What's left to do before I pull request it:

1. Fix UVS
2. have a start and end percentage along curve. 
3. right now it's pretty sensitive to the curve twisting, so need to add some methods to combat that, or you get some messed up results. This will probably mean a lock rotation check box, and start end twist scalars. 
3. we need a merge mesh node to make the most use of this, might work on that too. 
4. taper along curve, relatively easy to add, so might as well, would be good for pre-modeled and textured tree trunks. 

More ideas are welcome.

**Comment by Muzz** [comment]
I'm also going to make some raycasting nodes, so that we can cast vertexes along their normal until they collide with something. 

This will be good to make form fitting roads and things match height maps, or make curved level decals easily.

**Comment by HungryProton** [comment]
That would be great! How is it done? 
I had some issues with twisting in the extrude along curve node but the strategy I used my not work depending on how you achieved this

**Comment by Muzz** [comment]
It's remapping the y axis to a point along the curve, then using a rotational matrix to align the verts to the curve direction. 

If i don't come up with anything maybe you can have a look at the strategy when I do the pull request.

**Comment by HungryProton** [comment]
How do you calculate the curve direction? 

What I did with extrude_along_curve is: I placed a transform at the beginning of the path, and another one a bit further along, called look_at_from_position() from the first transform to the second one. 
look_at needs an up vector so the first call uses Vector3.UP, and every successive calls uses the previous transform up vector. This part removed the twisting I had.

Now I have no idea if any of this could be useful to you, look_at is implemented there https://github.com/godotengine/godot/blob/00949f0c5fcc6a4f8382a4a97d5591fd9ec380f8/core/math/transform.cpp#L79 but my math skills are useless there

**Comment by Muzz** [comment]
Ah, I was wondering what was going on there. I'll give it a play and see what I can come up with Thanks!

Is there any other mesh modification nodes you can think of as being helpful? I enjoy this stuff.

**Comment by Muzz** [comment]
Did a pull request for the first version. 

![image](https://user-images.githubusercontent.com/2074204/82141840-c747eb00-987b-11ea-9b54-ad04d3697d6e.png)

**Features:**
- It correctly handles normals.
- it uses the up vector of godot's curves make sure it's on
- it uses the tilt of godot's curves, sadly these aren't exposed to the editor, but it should work. This means that you can potentially rotate each point separately
- It has a rotate control
- start end range. 

**Todo:**
- Vector 3 input to set the initial axis. It currently uses the Y axis. Might not be ideal. 
- Scale the object relative to the curve
- 2d curve to scale object along curve
- Absolute mode, so it doesn't stretch the objects
- Flip vert winding and normals when range is inverted


Give it a try, and give me feedback on how to improve it.

**Comment by HungryProton** [comment]
This is awesome! Thank you for the PR

Using the tilt of the curve is a great idea, the default path gizmo doesn't expose it but that's something I may be able to add myself by reusing some old code from a previous add-on, at some point It should also be possible to store scaling data on each points of the curve, but, that's for later.

If you want to add functions that can be reused in other nodes, like converting a primitive mesh to an array mesh, you can create a mesh_util.gd script in src/common/. Make it a static function to make it easier to call from your node.

The code itself looks good. This is the first complex custom node that's submitted, so I'd like to have your feedback on whether there's enough functionality exposed or if there are things that doesn't make sense or could be improved.

**Comment by Muzz** [comment]
Scaling data per point is a great idea too! That would be really helpful. 

Honestly everything was easy to implement, it felt very transparent to just work on it as I just had access to the raw godot functions. As I see it right now it's a pure function, where I get clean inputs and clean outputs and it doesn't get much cleaner than that. 

I copied some logic from some other nodes and just went from there. 
Registering the node entirely inside the script was a great move too, makes it very extensible. 
The one main thing I'd like is just some immediate drawn debug nodes, so I could just call something like debug_line(start,end). 

I think right now the hardest thing is just thinking about what functionality to build in haha.
