### ISSUE TITLE
Saving output as tscn

### ISSUE THREAD

**Issue by christinoleo** [HungryProton/concept_graph#41]
I did a little addition to my workflow by letting an output node to save the result as a .tscn file. It is useful to me and I believe it should be helpful for more people. I can send a pull request if deemed worthwhile.

**Comment by HungryProton** [comment]
It would definitely be useful. How does it work? Did you added a tool script on the output node and exported a file path where the output is saved?

**Comment by christinoleo** [comment]
I (unknowingly) sent the change in pr #40 .
