### ISSUE TITLE
Export and import as gltf2 node

### ISSUE THREAD

**Issue by fire** [HungryProton/concept_graph#43]
I have tooling to do this in an engine branch, but I don't have the personal bandwidth to port the engine module to gdnative.

https://github.com/godot-extended-libraries/gltf/tree/ae821b1ec58ece1d5ea8fe2dc9107c68051d55e6

**Comment by HungryProton** [comment]
That's an often requested feature. I'm adding it to the roadmap but I don't know when I will actually have time to port it

**Comment by HungryProton** [comment]
Added in ac0e5b2ec7f92cb6069d518033bd52b822b50033
