### ISSUE TITLE
Reduce mesh triangles node

### ISSUE THREAD

**Issue by fire** [HungryProton/concept_graph#44]
https://github.com/godot-extended-libraries/mesh_lod/tree/ffac1121bac30da7a89cc6fce29cbfff12d1eeb7

Features:

* Reduce triangles
* Reduce triangles ignoring topography

Do not have the bandwith to port to GDNative.

**Comment by wojtekpil** [comment]
This is really amazing. It's a must have feature for parametric generator like this. I think integration with the concept-graph would result in great performance improvements. I also agree that, the main problem is the way of implementation as an integral part of Godot. Most users are not as advanced or simply don't want to compile the engine from scratch. Implementation in the form of GDNative (with support for at least WIN / OSX / LINUX) certainly would arouse much greater interest. Unfortunately, I have never written or compiled the GDNative plugin before.

**Comment by HungryProton** [comment]
This would be a great addition for sure!
I never used GDNative before but I'll take a look when I have more time

**Comment by fire** [comment]
Out of the three proposals, this has the smallest amount of code. I can feasibly port this in a shott time.

**Comment by fire** [comment]
Can you help design the node interface?

So here are possible attributes

* decimation percent
* is_sloppy

**Comment by fire** [comment]
What is the format of the mesh and materials?

**Comment by HungryProton** [comment]
Usually, plain MeshInstances 
Materials are anything that inherits the built in Material class

**Comment by fire** [comment]
I got it to simplify as a gdnative module. Sloppy simplification (forced) isn't ready yet, but topographical following is.

**Comment by fire** [comment]
https://github.com/fire/concept_graph

**Comment by fire** [comment]
```
extends Spatial


func _on_Timer_timeout():
	var mesh_optimize = preload("res://addons/concept_graph/native/bin/win64/mesh_optimize.gdns").new()
	mesh_optimize.optimize("res://test.tscn", self)
	get_tree().quit()
```
This is the current api. Please advise?

**Comment by HungryProton** [comment]
What do you want to know exactly? 
I haven't look at the code yet but does mesh_optimize only works with a whole scene? If it can accept a MeshInstance directly it would be much simpler. If it can't, then I guess you have to save the MeshInstance as its own packed scene, run it through the external lib, and load it back afterwards.

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/82160462-6bb13980-984a-11ea-8fc9-6ae2f2a33e11.png)

I added a specific threshold optimization value. Will output a mesh instance directly in a bit.

**Comment by Muzz** [comment]
Nice work.

**Comment by fire** [comment]
This is the api I'm thinking of exposing. I'll show you a gdscript version in a bit.
```c++
void optimize(const String p_file, Node *p_root_node, float p_threshold = 1.0f);
Ref<ArrayMesh> optimize_mesh(Ref<Mesh> p_mesh, float p_threshold = 1.0f);
MeshInstance *optimize_mesh_instance(Ref<Mesh> p_mesh, float p_threshold, NodePath p_skeleton_path, String p_name, Ref<Skin> p_skin);
void simplify(Node *p_root_node, float p_threshold = 1.0f);
```

**Comment by fire** [comment]
```
extends Spatial


func _on_Timer_timeout():
	var mesh_optimize = preload("res://addons/concept_graph/native/bin/win64/mesh_optimize.gdns").new()
	var mi : MeshInstance = get_node("BoomBox")
	var output_mi = mesh_optimize.optimize_mesh_instance(mi.mesh, 0.1, mi.skeleton, mi.name, mi.skin)
	print(output_mi.name)
```

**Comment by HungryProton** [comment]
Nice! That API should be more than enough :smiley:

**Comment by fire** [comment]
Will work on sloppy simplification. (forced).

**Comment by wojtekpil** [comment]
Yes that's really great. It's a first step for procedural chipping in Godot. As for the code, I would suggest determining a project structure for GDNative nodes in a Concept-Graph. Maybe something like native/plugin_name/ ? And any larger plugin could be a git sub-module.

**Comment by fire** [comment]
```swift
extends Spatial


func _ready():
	var mesh_optimize = preload("res://addons/concept_graph/native/bin/win64/mesh_optimize.gdns").new()
	var mi : MeshInstance = get_node("BoomBox")
	var output_mi : MeshInstance = mesh_optimize.optimize_mesh_instance(mi.mesh, 0.9, mi.skeleton, mi.name, mi.skin, true)
	print(output_mi.name)
	output_mi.transform = mi.transform
	mi.visible = false
	add_child(output_mi)
```

![image](https://user-images.githubusercontent.com/32321/82161482-f2b5e000-9851-11ea-9f22-2783a779bd35.png)

Sloppy optimization gives no cares for topography :D.

PS. Not a fan of submodules :(. They cause so much pain.

**Comment by HungryProton** [comment]
Great job!

Regarding sub-modules, the only thing I don't want to carry around in the 200k lines of godot-cpp bindings, this should be its own sub-module.
Third-party libraries can be included as is, it's better for compatibility anyway.

New custom nodes should stay in GDScript, in the same src/nodes/ folder, they simply call the GDNative library from the generate_outputs method. 
GDNative libraries should go in their own folder, probably under concept_graph/src/native I guess

**Comment by fire** [comment]
Updated: https://github.com/fire/concept_graph/commit/cbdd84a1e01feea081e9505d8699251246303851

**Comment by wojtekpil** [comment]
Yes, when I was talking about gdnative nodes I meant the libraries. As for the sub-modules, I was rather speaking about integration of already existing libraries with its own git repositories, not those created specifically for concept-graph. Personally I prefer google repo command but git submodules are probably more popular.

**Comment by fire** [comment]
Before I forget, this reduction is currently in LOD mode, but it can also be baked. Currently, all of the calls of the mesh_instance with different thresholds can be used as a lod for the same grouping.

**Comment by fire** [comment]
Add a hack for the mesh corners being removed. The C++ hack improves simplification quality.

**Comment by HungryProton** [comment]
This feature was added to the develop branch, thank you for porting the code!

**Comment by fire** [comment]
Feel free to modify https://github.com/HungryProton/concept_graph/blob/develop/src/native/src/mesh_optimize.cpp to use your standard license header.

I suggest copying https://github.com/fire/godot/blob/scene_export_native_gltf/AUTHORS.md 's concept of authors and changing the license to add a line like below.

```
Copyright (c) 2014-2020 Concept Graph contributors (cf. AUTHORS.md).
```
