### ISSUE TITLE
Expand Curve node does nothing

### ISSUE THREAD

**Issue by Astavie** [HungryProton/concept_graph#47]
https://github.com/HungryProton/concept_graph/blob/dc11d105433f1991c2c4c081ed58cfaff086c3b7/src/nodes/curves/expand_curve.gd#L26

**Comment by HungryProton** [comment]
Oh, I pushed that by mistake, it shouldn't be there yet. Same goes for the smooth curve node.
Adding that to the todo list

**Comment by HungryProton** [comment]
Smooth curve and Expand curve were added in 144f7bf1c3714d618042e709dcb9b310f4ea4c21
