### ISSUE TITLE
Node 3d input clears Scalar and Boolean inputs (attach/detach/load)

### ISSUE THREAD

**Issue by BryceBubbles** [HungryProton/concept_graph#48]
Attaching and detaching a Node 3d input will clear Scalar and Boolean inputs on the same node to their default.

This clearing also happens on graph load, so it feels like state isn't saving, but if the Node 3d input isn't attached the Scalar and Boolean inputs will load their saved state.

Checked on Godot 3.2-stable with a new project and clean install of concept_graph 0.3-alpha.

Some example nodes and the inputs that get cleared:
- Exclude from noise - Threshold, Invert, Local space
- Set material - Override children
- Rotate random - Seed, Local Space
- Offset - Negative, Local space
- Spawn random duplicates - Seed

Parent to node also bugs out when attaching/detaching inputs.

I'm guessing this has something to do with the new dynamic slot system?

**Comment by HungryProton** [comment]
Yes this is probably because of the dynamic slot system. I didn't test this enough it seems. I'll make a patch tonight

**Comment by HungryProton** [comment]
Should have been fixed in c79993de9861813e106e51dbd09e87248272b22f
