### ISSUE TITLE
Load and Create buttons next to Clear all 

### ISSUE THREAD

**Issue by BryceBubbles** [HungryProton/concept_graph#49]
There's no way to load a graph on an already setup ConceptGraph node. 

Originally I thought the Clear all button should show the Load and Create buttons you get when adding a ConceptGraph node to a scene?

But then I noticed that the Create button requires you to save the graph, so the Clear all button has a very different function. 

So perhaps Load and Create buttons could be added next to the Clear all button?

**Comment by HungryProton** [comment]
I could add a button for that. For now the only way to remove a template is to select the ConceptGraph node in the scene tree and clear the template path variable

**Comment by HungryProton** [comment]
Added in 3b4c185f735ddc13a2873c18a1a88ac0bcae5002
