### ISSUE TITLE
Scale along curve

### ISSUE THREAD

**Issue by danreeves** [HungryProton/concept_graph#60]
I was wondering if scaling along a curve was a feature you were considering. As an example: making the branches at the top of the tree smaller than the lower ones.

I made a rough implementation quickly, but I'm not sure if it's the best way:

```gdscript
tool
extends ConceptNode


func _init() -> void:
	unique_id = "scale_along_curve"
	display_name = "Scale along curve"
	category = "Transforms"
	description = "Scales nodes along a curve"

	set_input(0, "Nodes", ConceptGraphDataType.NODE_3D)
	set_input(1, "Curve", ConceptGraphDataType.CURVE_2D)
	set_output(0, "", ConceptGraphDataType.NODE_3D)

	mirror_slots_type(0, 0)


func _generate_outputs() -> void:
	var nodes := get_input(0)
	var curve: Curve = get_input_single(1, 0)
	var local_transform: bool = get_input_single(2, true)

	if not nodes or nodes.size() == 0:
		return
		
	for i in range(nodes.size()):
		var curve_point = curve.interpolate_baked(float(i) / float(nodes.size()))
		nodes[i].transform = nodes[i].transform.scaled(Vector3(curve_point, curve_point, curve_point))
	output[0] = nodes
```

**Comment by HungryProton** [comment]
Not something I considered but it could be added, there's no such things as too many nodes!

The issue with this script is it only works if all the nodes passed in inputs are already ordered and at equal distance from each other and there's absolutely no guarantee of that. If you pass a grid point in input, it just going to scale things in order they were added in the array.

However, with an extra curve3D parameter, you could pass the trunk path object to this, and then on each node, call path.curve.get_closest_point(node.position) to get the closest point on the curve from this node, check how far it is along the curve, and get the scaling value from the curve2D, that would work

**Comment by danreeves** [comment]
Oh I see what you're saying. I'll give it a go

**Comment by danreeves** [comment]
Updated node to take a Path:

```gdscript
tool
extends ConceptNode


func _init() -> void:
	unique_id = "scale_along_curve"
	display_name = "Scale along curve"
	category = "Transforms"
	description = "Scales nodes along a curve"

	set_input(0, "Nodes", ConceptGraphDataType.NODE_3D)
	set_input(1, "Path curve", ConceptGraphDataType.CURVE_3D)
	set_input(2, "Scale curve", ConceptGraphDataType.CURVE_2D)
	
	set_output(0, "", ConceptGraphDataType.NODE_3D)

	mirror_slots_type(0, 0)


func _generate_outputs() -> void:
	var nodes := get_input(0)
	var curve_path: Path = get_input_single(1, 0)
	var scale_curve: Curve = get_input_single(2, 0)

	if not nodes or nodes.size() == 0:
		return
		
	add_child(curve_path)
	for i in range(nodes.size()):
		add_child(nodes[i])
		var local_position = curve_path.to_local(nodes[i].global_transform.origin)
		var along_curve_path = curve_path.curve.get_closest_offset(local_position) / curve_path.curve.get_baked_length()
		var curve_point = scale_curve.interpolate_baked(along_curve_path)
		
		nodes[i].transform.basis = nodes[i].transform.basis.scaled(Vector3(curve_point, curve_point, curve_point))
		remove_child(nodes[i])
		
	output[0] = nodes
	remove_child(curve_path)
```

I ended up only scaling the transform basis so that the position of the node doesn't change too. I don't know if that would ever be desirable, but it could be an option.

Are you open to a PR for this?

**Comment by danreeves** [comment]
An example of something made with this:
![image](https://user-images.githubusercontent.com/1973559/82761166-822e3680-9df0-11ea-80d0-6e7d85dcfece.png)

**Comment by Muzz** [comment]
Very nice. Good work! I should build this functionality into the deform along curve code too. 

I'm not the maintainer but i'd say just go ahead and make the PR.

**Comment by HungryProton** [comment]
Looks good to me! Feel free to make a PR directly.

I'm not really sure how transform scaling works in Godot though, I usually just call transform.scaled() and move the origin around. I don't know if it's recommended or not, couldn't find too many details on it. But as long as it works and it behaves the same way, I don't see any issue with it.

**Comment by danreeves** [comment]
Opened #64

**Comment by HungryProton** [comment]
Closing the issue as the pull request was merged
