### ISSUE TITLE
Error: Node type [custom node name] could not be found.

### ISSUE THREAD

**Issue by danreeves** [HungryProton/concept_graph#61]
After reloading the plugin and opening a scene with a Concept Graph using a custom node I wrote it would delete that node from the graph with the warning `Error: Node type scale_along_curve could not be found.`.

The node _is_ in the library however, since I can add it again.

Not sure if this is a naming convention issue or something.

**Comment by danreeves** [comment]
It seems like the issue is that the script file name and the node unique_id must match

**Comment by HungryProton** [comment]
I have this issue too and I have to restart Godot every time I create a new node script. I suspect it's because of the node library not being properly cleaned between each reloads but I haven't looked into it further

**Comment by HungryProton** [comment]
Node library now properly re-scan the whole nodes folder when reloading the plugin.
