### ISSUE TITLE
Merge some Transform nodes?

### ISSUE THREAD

**Issue by BryceBubbles** [HungryProton/concept_graph#65]
@HungryProton we discussed a `Position from noise` node here: https://github.com/HungryProton/concept_graph/pull/59#issuecomment-633555264

But is adding a separate node for this a good idea?
Or should there be a `Transform from Noise` node that's like the `Edit Transform` node? 

That brings me to the broader question in the title:

**Should these Transform nodes (as well as the missing one):**

- Offset, Rotate, Scale
- Jitter, Rotate random
- Scale from noise

**be merged into nodes that handle the complete Transform:**

- `Transform (All)` -  _just "Edit Transform" renamed_
- `Transform (Random)`
- `Transform (Noise)`
- `Transform (Offset)` - _just an idea, but this one could transform each node with an Additive or Multiplicative offset, based on the nodes current position from a given vector_

**Then could/should the individual node be removed?**
There's a bunch of pros and cons to this question, which I was going to list here, but wont unless you'd like to discuss them.

**Note: I can work on this if you'd like?**

**Comment by HungryProton** [comment]
So the question is **Should we have a few multipurpose nodes or many smaller ones with a single responsibility** ?

I think the smaller the better but without proper conventions that causes issues
![image](https://user-images.githubusercontent.com/52043844/82894563-0e586f00-9f53-11ea-85d6-d06c32d5801d.png)

Right now, there's no consistency in the titles, slots names or available options which makes it harder to find what node we're looking for. This is probably what should be fixed, not only for the transforms but for all the nodes.

Merging the offset / rotate / scale node in a single one could be possible, the inputs become
- transforms (node 3D)
- position (vector3)
- rotation (vector3)
- scale (vector3)
- local space (bool)

I think 5 inputs is still reasonable but as soon as we add more features it starts to get big. I don't really know how similar software handle this, it would be nice to have comparisons with the outside.

**Comment by BryceBubbles** [comment]
I like the idea of having less nodes to consider.

More inputs does make the nodes take up more visual space, which might be annoying if you only need to modify a single property.

But if you need to modify all three properties, then less space is taken up, it's less clicks to set up, and performance should be slightly better if the node uses a single loop.

Also if you decide later to modify another property, then you don't have to make room for another transform type node, just a vector node. 

I'm ok with keeping the single purpose ones as well if you think we should. 

If we do, we just need to get naming right so that listing order in the node menu is good. 

Note: I like capital case and not using joiner words where possible. 

Modifier first order (my preference):

- Edit Position
- Edit Rotation
- Edit Scale
- Edit Transform
- Noised Position
- Noised Rotation
- Noised Scale
- Noised Transform
- Random Position
- Random Rotation
- Random Scale
- Random Transform 

Property first order:

- Position
- Position Random
- Position Noised
- Rotate
- Rotate Random
- Rotate Noised
- Scale
- Scale Noised
- Scale Random
- Transform
- Transform Random
- Transform Noised

Let me know if you want me to work on this.

**Comment by HungryProton** [comment]
That's right we can just keep both. I like the naming convention, if you want to work on it go ahead. I don't know which issue interests you the most. I'll try avoid working on something big without mentioning it in the related issue so our work doesn't  overlap

**Comment by BryceBubbles** [comment]
Cool will work on getting this done by end of week (mid week is busy for me).
If you have time and want to get it sorted quicker, let me know, but I think you've got plenty of more complex features to work on ay?

**Comment by HungryProton** [comment]
Alright thanks! And yes, week days are busy for me too anyway

**Comment by HungryProton** [comment]
I don't think this will impact you in any way but just to let you know, I'm adding 2D nodes to the addon, most of them in their own Node2D folder.

Not sure yet if all the names should have a 2D / 3D suffix to make everything consistent (Like `Edit Transform 2D` and `Edit Transform 3D`)

**Comment by HungryProton** [comment]
Merged in 7672be2622bca89ac612c4d95afbe3e4ef4ae637
