### ISSUE TITLE
simple_tree example scene don't open if the plugin is activated

### ISSUE THREAD

**Issue by NewNodeGames** [HungryProton/concept_graph#87]
Godot 3.2.2
The scene opens without problem if the addon is not active but don't open and print this message in debug console if is activated:
"Object was deleted while awaiting a callback"

**Comment by HungryProton** [comment]
Go to your project settings, under **Memory -> Limits**, increase the Message queue max size to something like 4096 or higher
That's mentioned on the wiki but it should probably be at the top of the readme. That's something we won't have to worry about with the standalone version though.

**Comment by NewNodeGames** [comment]
ok, solved
