### ISSUE TITLE
Simple tree example freezes: "Object was deleted while awaiting a callback"

### ISSUE THREAD

**Issue by jmdejong** [HungryProton/concept_graph#88]
When creating a new empty project, adding the concept_graph plugin, and loading the simple_tree example scene godot freezes and ends up continuously printing "Object was deleted while awaiting a callback".

The start of the output looks like this:

	Godot Engine v3.2.2.stable.custom_build - https://godotengine.org
	Found discrete GPU, setting DRI_PRIME=1 to use it.
	Note: Set DRI_PRIME=0 in the environment to disable Godot from using the discrete GPU.
	OpenGL ES 2.0 Renderer: AMD OLAND (DRM 2.50.0, 5.7.8-arch1-1, LLVM 10.0.0)
	OpenGL ES 2.0 Batching: ON
	
	ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
		At: scene/main/node.h:281.
	ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
		At: scene/main/node.h:281.
	ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
		At: scene/main/node.h:281.
	ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
		At: scene/main/node.h:281.
	ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
		At: scene/main/node.h:281.
	ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
		At: scene/main/node.h:281.
	Failed method: VBoxContainer:_update_minimum_size target ID: 59680
	Object was deleted while awaiting a callback
	Object was deleted while awaiting a callback
	Object was deleted while awaiting a callback
	Object was deleted while awaiting a callback
	Object was deleted while awaiting a callback
	Object was deleted while awaiting a callback
	Object was deleted while awaiting a callback

(The first 5 lines are just from starting up the engine).
This is followed by a lot more "Object was deleted while awaiting a callback" functions.
It looks like this is printed from a neverending loop.

The same happens with the simple_tree_forest example.
The palm_tree example works fine.

When I disable the plugin before loading the scenes the scenes load fine.
it still prints some errors:

	ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
		At: scene/main/node.h:281.
	ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
		At: scene/main/node.h:281.
	ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
		At: scene/main/node.h:281.
	ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
		At: scene/main/node.h:281.
	ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
		At: scene/main/node.h:281.
	ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
		At: scene/main/node.h:281.
	ERROR: get_node: Node not found: ConceptNodeLibrary.
		At: scene/main/node.cpp:1381.
	ERROR: get_node: Node not found: ConceptNodeLibrary.
		At: scene/main/node.cpp:1381.

When I then enable the plugin and try to look in the concept graph editor I only see an empty graph.

**Comment by HungryProton** [comment]
Go to your Project Settings > Memory > Limits, increase the message queue size to 4096 at least
